### PR TITLE
Add hyper 0.11 support

### PR DESCRIPTION
**Pull request by sathiyan-sivathas**
I built this off of your hyper12 branch because it looked like it was closer to what I needed. `Connect` isn't a trait you implement in hyper 0.11, you implement `client::Service` instead. That's the bulk of the change.

Builds locally for me and I've tested that it works in our project.

### CODE REVIEW

**Review by cswindle — CHANGES_REQUESTED** [review]
Looks good, can you switch to master for the PR as merging to a hyper12 branch is not that sensible (although it was useful to see the delta).

**Comment by sathiyan-sivathas** [comment]
I've updated.

**Review by cswindle — APPROVED** [review]

**Comment by cswindle** [comment]
Done and published as 0.3.0 on crates.io.

**Comment by sathiyan-sivathas** [comment]
Thanks!

**Pull request merged**
